feat: test summary
zoncoen/scenarigo pull request #395
Opened 2024-02-16 15:07 UTC by kyu08

This is an implementation of #.
This implementation adds output like this.

| Case | Image |
|--------|--------|
|When all tests passed| <img width="769" alt="image" src="https://github.com/zoncoen/scenarigo/assets/49891479/42dbb843-1868-4f5b-a53b-470e19820c73">|
|When some tests failed|<img width="630" alt="image" src="https://github.com/zoncoen/scenarigo/assets/49891479/bd661ff6-5a15-40d5-8bc0-e7a3d3485f58">|

If this feature request is acceptable, I will polish up this PR on these points.
- Make this feature configurable.
- If `colored: true` , outputs with some colors.
- Add some unit tests.

Thank you.

2024-02-19 16:27 UTC, zoncoen commented
Thank you for your proposal!
As you suggested, it should be configurable. Please add an option to `OutputConfig`.

https://github.com/zoncoen/scenarigo/blob/ffdb628865654047c3e26b05c14d952cbdb60263/schema/config.go#L57-L61

2024-02-20 17:22 UTC, kyu08 commented
I will add few changes to this PR.
After I finished it I will reopen this PR.
Please review these changes after that. 🙏

2024-02-21 04:01 UTC, zoncoen requested changes

2024-02-21 04:05 UTC, zoncoen commented on schema/config.go
> +	NoSummary bool         `yaml:"noSummary,omitempty"`
Please insert `Summary` field into the line below `Colored`.

2024-02-23 14:35 UTC, kyu08 commented on schema/config.go
> +	NoSummary bool         `yaml:"noSummary,omitempty"`
Fixed in cdf2703b061050efce6c8f45f82e5112b1b0da07

2024-02-23 14:36 UTC, kyu08 commented on cmd/scenarigo/cmd/config/default.scenarigo.yaml
> +  noSummary: false # Disable show summary.
Fixed in cdf2703b061050efce6c8f45f82e5112b1b0da07.

2024-02-23 15:25 UTC, kyu08 commented on runner.go
> +	w               io.Writer
Thank you for letting me know the difference of responsibilities of Runner and `reporter`.

This point was fixed in 8a0294b673ba5a612edd71a67f8e63468e7b5e32.

2024-02-23 15:38 UTC, kyu08 commented
## TODO
- [ ] Fix CI errors.
- [ ] Add unit tests.
- [ ] Update README
    - [ ] Update code snippet generated by `scenarigo init` in `## Setup`

2024-02-25 07:38 UTC, kyu08 commented
@zoncoen
I'm done with TODOs and the changes you pointed.
This is a summary of changes after your first review.

- implement `PrintSummary` as `reporter`'s method(ce5ca6c)
- fix existing tests's errors caused by my changes (1fa298c, 5e91e6d)
- update readme (bb761bb)
- change `testSummary#add`'s argument(`r reporter.Reporter` to `testResultString string`) for the testability (6d2ac7f)
- add unit tests (a3713ee, b9375b0, f2d457b)
- format(5f31d8e)

Could you review again please?

2024-02-26 16:09 UTC, zoncoen requested changes
Please implement the logic to print a summary in the `reporter` package (not `scenarigo` package). I think it is enough like the following code.

```func run(cmd *cobra.Command, args []string) error {
	// ...
	if cfg.Output.Summary {
		reporterOpts = append(reporterOpts, reporter.WithTestSummary())
	}

	var reportErr error
	success := reporter.Run(
		func(rptr reporter.Reporter) {
			r.Run(context.New(rptr))
			reportErr = r.CreateTestReport(rptr)
		},
		reporterOpts...,
	)
	// ...
}```

https://github.com/zoncoen/scenarigo/blob/3f72845f973421774eecda4a60f222482e8ae5e2/cmd/scenarigo/cmd/run.go#L34

```func (r *reporter) runWithRetry(name string, f func(t Reporter), policy RetryPolicy) bool {
	// ...
	if r.isRoot() {
		printReport(child)  // This is 
		if r.context.summary {
			printSummary()
		}
	}
	return !child.Failed()
}```

https://github.com/zoncoen/scenarigo/blob/3f72845f973421774eecda4a60f222482e8ae5e2/reporter/reporter.go#L265

2024-02-27 05:27 UTC, kyu08 commented
Thank you for your feed back!

> Please implement the logic to print a summary in the reporter package (not scenarigo package). I think it is enough like the following code.

I'm sorry for misunderstood your advice. I'll fix it.

Also, thank you for showing me code examples kindly.
I tried to print `test message` in a way like your second code snippet like this.
```go
func (r *reporter) runWithRetry(name string, f func(t Reporter), policy RetryPolicy) bool {
        // ...
	if r.isRoot() {
		printReport(child)
		r.context.printf("%s\n", "\ntest message\n")
	}
	return !child.Failed()
}
```

But it seems like `test message` was showed after every test file execution like below.
<img width="828" alt="image" src="https://github.com/zoncoen/scenarigo/assets/49891479/9beeb620-66d8-4f4a-ae68-9ad3b1ee683b">

How about call `printSummary` [here](https://github.com/kyu08/scenarigo/blob/f2d457bb2a3f96916ca463c468e7dc29ab52fcfd/reporter/reporter.go#L56) and  call `printSummary#add` [here](https://github.com/kyu08/scenarigo/blob/f2d457bb2a3f96916ca463c468e7dc29ab52fcfd/reporter/reporter.go#L284)?

When I change to call `r.context.printf` in `Run` func like below.
```go
// reporter/reporter.go
func Run(f func(r Reporter), opts ...Option) bool {
	r := run(f, opts...)
      	r.context.printf("test message called in Run func\n")
	return !r.Failed()
}
```
Then `test message` was shown just once properly.
<img width="696" alt="image" src="https://github.com/zoncoen/scenarigo/assets/49891479/5bb2b52c-2ecd-4f1f-b2e3-e61199e6d6b7">

2024-02-27 07:07 UTC, zoncoen commented
Ah~ you're right. It's OK to print a summary in `Run` func 👍

2024-02-27 10:06 UTC, kyu08 commented
I fixed to  implement test summary logic in the `reporter` package.
And I added some minor changes. Please check it out.

### About the naming `summary` versus `testSummary` c138756506be77d13e8650f6991937d8e410952c
I used the naming `summary` in the context of configuration, and I used the naming `testSummary` in other contexts.
Because I feel like it is natural that the naming `summary` means this test summary feature in the config context, on the other hand it seems unnatural in the context of whole code base.

If you have any thought, please give me an idea🙏

2024-02-27 16:13 UTC, zoncoen requested changes

2024-02-27 16:13 UTC, zoncoen commented on reporter/reporter.go
> +		child.context.testSummary.append(name, TestResultString(child))
I don't want to keep any data if the summary feature is disabled. How about like below?

```go
func (s *testSummary) append(testFileRelPath string, r Reporter) {
	if s == nil {
		return // disalbed
	}
	testResultString := TestResultString(r)
	// ...
}
```

2024-02-27 16:13 UTC, zoncoen commented on reporter/test_summary.go
> +}
It is sufficient to count only for passed and skipped. Filenames are needed only for failed.

2024-02-28 12:33 UTC, kyu08 commented on reporter/reporter.go
> +
🙏 
Fixed in 151da5ad3fdf94747b602d83616cbc09d5961fe6.

2024-02-28 13:26 UTC, zoncoen commented on reporter/context.go
> +}
> I understand you mean testSummary struct should not have enabledColor field and testContext.noColor's value should be passed to testSummary#String as needed.

That's right. In other words, `reporter. WithNoColor` option should control all output.

> So I feel there is no point to change about this.

The new implementation is also acceptable. 👍

2024-02-28 15:16 UTC, kyu08 commented on reporter/reporter.go
> +		child.context.testSummary.append(name, TestResultString(child))
Fixed in aca2ad33f985c60f2d3daa30938fd1ebe9e42bf4.

2024-02-28 15:21 UTC, kyu08 commented on reporter/test_summary.go
> +}
Fixed in 8d95a95e1a3b64b662f2a119d3e9e0aa703313f8.

2024-02-28 15:40 UTC, zoncoen approved these changes
Thank you for taking the time and patience to bring this into the final shape!
LGTM 💯

2024-02-28 15:55 UTC, merged

2024-02-28 16:03 UTC, kyu08 commented
Thank you for reviewing my clumsy code using your precious time too!🙏
And I'm sorry that lack of understanding of this project of me leads increasing time and labor to review this PR.
I probably can deal with it more smoothly next time, so I am willing to contribute if there is an issue I can solve.

2024-03-17 15:23 UTC, kyu08 commented
Thank you for reviewing my pull request the other day. I'm looking forward to using the test summary feature, and I’d really appreciate it if you could roll out the next version when it’s feasible. 
Thank you.